before_script:
  - apt-get update -qq && apt-get install -y -qq cmake
  - git clone https://github.com/zorgnax/libtap.git && cd libtap && make && make install && cd ..
  - ldconfig
stages:
  - build
  - test
build_job:
  stage: build
  script:
    - cmake .
    - make
test_job:
  stage: test
  script:
    - cmake .
    - make && make test
    - cd test && ctest
